services:
  db:
    build: ./database
    ports:
      - "58923:58923"
    environment:
      TZ: "Asia/Tokyo"
    env_file:
      - .env.local
    volumes:
      - /var/lib/mysql
      - ./database/my.cnf:/etc/my.cnf
