version: '3.8'
services:
  db:
    build: ./database
    ports:
      - "58923:58923"
    environment:
      TZ: "Asia/Tokyo"
    env_file:
      - .env.local
    restart: always
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/my.cnf